# Generated by Django 5.2.8 on 2025-11-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="invoices/%Y/%m/%d/", verbose_name="发票文件"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
            ],
            options={
                "verbose_name": "发票凭证",
                "verbose_name_plural": "发票凭证",
            },
        ),
        migrations.CreateModel(
            name="Reimbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=200, verbose_name="活动主题")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="活动主要内容"),
                ),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="所属部门"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("SUBMITTED", "待处理"),
                            ("PACKED", "已打包"),
                            ("REJECTED", "已驳回"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="总金额",
                    ),
                ),
                (
                    "reviewer_note",
                    models.TextField(blank=True, verbose_name="审核备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "报销单",
                "verbose_name_plural": "报销单管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReimbursementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="物品名称")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="数量"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="金额",
                    ),
                ),
            ],
            options={
                "verbose_name": "报销明细",
                "verbose_name_plural": "报销明细",
            },
        ),
    ]
