# Generated by Django 5.2.8 on 2025-11-21 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claims", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursement",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reimbursements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="申请人",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reimbursement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="claims.reimbursement",
                verbose_name="报销单",
            ),
        ),
        migrations.AddField(
            model_name="reimbursementitem",
            name="reimbursement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="claims.reimbursement",
                verbose_name="报销单",
            ),
        ),
    ]
