# Generated by Django 4.2.26 on 2025-11-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="college",
            field=models.CharField(
                default="环境学院", max_length=100, verbose_name="学院"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(max_length=100, verbose_name="部门"),
        ),
    ]
